In [9]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import multiprocessing as mp
import os
import seaborn as sns

from jqdatasdk import *
# auth('15397649986','dd111477')
# auth('18200571595','571595')
auth('17780620786','xxb19880825')
%matplotlib inline
%config InlineBackend.figure_format = 'svg'

In [10]:
IO9999 = get_price('IO9999.XSHG','2018-12-21 09:00:00','2018-12-21 12:00:00','1m')

Exception: 找不到标的IO9999.XSHG

In [2]:
futures = list(get_all_securities(['futures']).index)
futures[:10]

['A0501.XDCE',
 'A0503.XDCE',
 'A0505.XDCE',
 'A0507.XDCE',
 'A0509.XDCE',
 'A0511.XDCE',
 'A0601.XDCE',
 'A0603.XDCE',
 'A0605.XDCE',
 'A0607.XDCE']

In [3]:
num = []
for i in futures:
    num.append(len(i))
set(num)

{10, 11}

## CU all

In [9]:
futures[1][0]=="A"

True

In [4]:
cu_futures=[]
for i in range(len(futures)):
    if futures[i]=="IC9999.CCFX":
        cu_futures.append(futures[i])
len(cu_futures)

1

In [11]:
# cu_futrue.index()
cu_futures[:5]

['CU0501.XSGE', 'CU0502.XSGE', 'CU0503.XSGE', 'CU0504.XSGE', 'CU0505.XSGE']

In [12]:
# CU0501 = get_bars(cu_futures[0], 10, unit='1m',
#           fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
#           include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [13]:
# for i in cu_futures:
#     print(cu_futures.index(i))
cu_futures.index('CU1912.XSGE')

179

In [5]:
for i in cu_futures[0:3]:
    a=r'/Users/tjmask/Desktop/quantitative strategy/data/'+i+'.csv'
    print(a)

/Users/tjmask/Desktop/quantitative strategy/data/IC9999.CCFX.csv

In [7]:
for i in cu_futures:
    a = r'/Users/tjmask/Desktop/quantitative strategy/cu_all/'+ i + '.csv'
    i = get_bars(cu_futures[cu_futures.index(i)], 500000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)
    i.to_csv(a)

In [ ]:
import datetime
AG9999 = get_bars(target_futures[1], 500000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

0.25

In [3]:
# target_futures=[]
# for i in range(len(futures)):
#     if len(futures[i]) ==10 and futures[i][1:5]=='9999':
#         target_futures.append(futures[i])
#     elif len(futures[i]) ==11 and futures[i][2:6]=='9999':
#         target_futures.append(futures[i])

In [4]:
len(target_futures)

70

In [7]:
target_futures[29:40]

['JR9999.XZCE',
 'L9999.XDCE',
 'LR9999.XZCE',
 'M9999.XDCE',
 'MA9999.XZCE',
 'ME9999.XZCE',
 'NI9999.XSGE',
 'NR9999.XINE',
 'OI9999.XZCE',
 'P9999.XDCE',
 'PB9999.XSGE']

In [71]:
# start_date = '2007-01-01'
# end_date = '2007-01-05'
# price_df = get_price(target_futures[0], start_date=start_date, end_date=end_date, 
#                      frequency='daily', fields=['close', 'money'], skip_paused=False, fq='pre', count=None)
# price_df

             close         money
2007-01-04  2815.0  2.282708e+09
2007-01-05  2834.0  1.851781e+09

In [93]:
import datetime
AG9999 = get_bars(target_futures[1], 1000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [108]:
AL9999 = get_bars(target_futures[2], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [109]:
AP9999 = get_bars(target_futures[3], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [110]:
AU9999 = get_bars(target_futures[4], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [9]:
B9999 = get_bars(target_futures[5], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [11]:
BB9999 = get_bars(target_futures[6], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [12]:
BU9999 = get_bars(target_futures[7], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [18]:
C9999 = get_bars(target_futures[8], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [19]:
CF9999 = get_bars(target_futures[9], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [22]:
CJ9999 = get_bars(target_futures[10], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [23]:
CS9999 = get_bars(target_futures[11], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [24]:
CU9999 = get_bars(target_futures[12], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [25]:
CY9999 = get_bars(target_futures[13], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [26]:
EB9999 = get_bars(target_futures[14], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

//anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py:162: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
  return cls.__new__(cls, **d)

In [27]:
EG9999 = get_bars(target_futures[15], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [28]:
ER9999 = get_bars(target_futures[16], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [29]:
FB9999 = get_bars(target_futures[17], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [30]:
FG9999 = get_bars(target_futures[18], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [31]:
FU9999 = get_bars(target_futures[19], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [48]:
GN9999 = get_bars(target_futures[20], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [49]:
HC9999 = get_bars(target_futures[21], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [50]:
I9999 = get_bars(target_futures[22], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [51]:
IC9999 = get_bars(target_futures[23], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [52]:
IF9999 = get_bars(target_futures[24], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [54]:
IH9999 = get_bars(target_futures[25], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [55]:
J9999 = get_bars(target_futures[26], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [56]:
JD9999 = get_bars(target_futures[27], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [57]:
JM9999 = get_bars(target_futures[28], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [38]:
JR9999 = get_bars(target_futures[29], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [94]:
target_futures[29:40]

['JR9999.XZCE',
 'L9999.XDCE',
 'LR9999.XZCE',
 'M9999.XDCE',
 'MA9999.XZCE',
 'ME9999.XZCE',
 'NI9999.XSGE',
 'NR9999.XINE',
 'OI9999.XZCE',
 'P9999.XDCE',
 'PB9999.XSGE']

In [37]:
L9999 = get_bars(target_futures[30], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [5]:
# LR9999 = get_bars(target_futures[31], 2000000, unit='1m',
#           fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
#           include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [6]:
# M9999 = get_bars(target_futures[32], 2000000, unit='1m',
#           fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
#           include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [7]:
# MA9999 = get_bars(target_futures[33], 2000000, unit='1m',
#           fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
#           include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [8]:
# ME9999 = get_bars(target_futures[34], 2000000, unit='1m',
#           fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
#           include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [9]:
# NI9999 = get_bars(target_futures[35], 2000000, unit='1m',
#           fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
#           include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [10]:
# NR9999 = get_bars(target_futures[36], 2000000, unit='1m',
#           fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
#           include_now=False, end_dt='2019-06-30', fq_ref_date=None)

//anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py:162: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
  return cls.__new__(cls, **d)

In [11]:
# OI9999 = get_bars(target_futures[37], 2000000, unit='1m',
#           fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
#           include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [12]:
# P9999= get_bars(target_futures[38], 2000000, unit='1m',
#           fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
#           include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [13]:
# PB9999 = get_bars(target_futures[39], 2000000, unit='1m',
#           fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
#           include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [103]:
target_futures[39:50]

['PB9999.XSGE',
 'PM9999.XZCE',
 'PP9999.XDCE',
 'RB9999.XSGE',
 'RI9999.XZCE',
 'RM9999.XZCE',
 'RO9999.XZCE',
 'RR9999.XDCE',
 'RS9999.XZCE',
 'RU9999.XSGE',
 'SC9999.XINE']

In [14]:
# PM9999 = get_bars(target_futures[40], 2000000, unit='1m',
#           fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
#           include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [15]:
# PP9999 = get_bars(target_futures[41], 2000000, unit='1m',
#           fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
#           include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [16]:
# RB9999 = get_bars(target_futures[42], 2000000, unit='1m',
#           fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
#           include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [17]:
# RI9999 = get_bars(target_futures[43], 2000000, unit='1m',
#           fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
#           include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [18]:
# RM9999 = get_bars(target_futures[44], 2000000, unit='1m',
#           fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
#           include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [19]:
# RO9999 = get_bars(target_futures[45], 2000000, unit='1m',
#           fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
#           include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [20]:
# RR9999 = get_bars(target_futures[46], 2000000, unit='1m',
#           fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
#           include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [21]:
# RS9999 = get_bars(target_futures[47], 2000000, unit='1m',
#           fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
#           include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [22]:
# RU9999 = get_bars(target_futures[48], 2000000, unit='1m',
#           fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
#           include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [23]:
# SC9999= get_bars(target_futures[49], 2000000, unit='1m',
#           fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
#           include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [8]:
target_futures[49:60]

['SC9999.XINE',
 'SF9999.XZCE',
 'SM9999.XZCE',
 'SN9999.XSGE',
 'SP9999.XSGE',
 'SR9999.XZCE',
 'SS9999.XSGE',
 'T9999.CCFX',
 'TA9999.XZCE',
 'TC9999.XZCE',
 'TF9999.CCFX']

In [24]:
SF9999= get_bars(target_futures[50], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [25]:
SM9999= get_bars(target_futures[51], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [9]:
SN9999= get_bars(target_futures[52], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [33]:
SP9999= get_bars(target_futures[53], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [11]:
SR9999= get_bars(target_futures[54], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [26]:
SS9999= get_bars(target_futures[55], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [13]:
T9999= get_bars(target_futures[56], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [14]:
TA9999= get_bars(target_futures[57], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [15]:
TC9999= get_bars(target_futures[58], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [30]:
TF9999= get_bars(target_futures[59], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [17]:
target_futures[59:]

['TF9999.CCFX',
 'TS9999.CCFX',
 'UR9999.XZCE',
 'V9999.XDCE',
 'WH9999.XZCE',
 'WR9999.XSGE',
 'WS9999.XZCE',
 'WT9999.XZCE',
 'Y9999.XDCE',
 'ZC9999.XZCE',
 'ZN9999.XSGE']

In [18]:
TS9999= get_bars(target_futures[60], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [19]:
UR9999= get_bars(target_futures[61], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [20]:
V9999= get_bars(target_futures[62], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [21]:
WH9999= get_bars(target_futures[63], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [22]:
WR9999= get_bars(target_futures[64], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [23]:
WS9999= get_bars(target_futures[65], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [24]:
WT9999= get_bars(target_futures[66], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [25]:
Y9999= get_bars(target_futures[67], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [26]:
ZC9999= get_bars(target_futures[68], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [29]:
ZN9999= get_bars(target_futures[69], 2000000, unit='1m',
          fields=['date', 'open', 'close', 'high', 'low', 'volume', 'money', 'open_interest'],
          include_now=False, end_dt='2019-06-30', fq_ref_date=None)

In [29]:
LR9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/LR9999.csv")
M9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/M9999.csv")
MA9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/MA9999.csv")
ME9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/ME9999.csv")
NI9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/NI9999.csv")
NR9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/NR9999.csv")

OI9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/OI9999.csv")
P9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/P9999.csv")
PB9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/PB9999.csv")
PM9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/PM9999.csv")

PP9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/PP9999.csv")
RB9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/RB9999.csv")
RI9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/RI9999.csv")
RM9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/RM9999.csv")

RO9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/RO9999.csv")
RR9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/RR9999.csv")
RS9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/RS9999.csv")

RU9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/RU9999.csv")
SC9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/SC9999.csv")

In [36]:
# SS9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/SS9999.csv")
SF9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/SF9999.csv")

In [39]:
JR9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/JR9999.csv")

In [ ]:
# LR9999,M9999  ,MA9999 ,ME9999 ,NI9999 ,NR9999 ,OI9999 ,P9999, PB9999,
## PM9999 PP9999 ,RB9999 ,RI9999 ,RM9999 ,RO9999 ,RR9999 ,RS9999,RU9999,SC9999,
# , SS9999
#      SF9999,SM9999,

In [35]:
target_futures

['A9999.XDCE',
 'AG9999.XSGE',
 'AL9999.XSGE',
 'AP9999.XZCE',
 'AU9999.XSGE',
 'B9999.XDCE',
 'BB9999.XDCE',
 'BU9999.XSGE',
 'C9999.XDCE',
 'CF9999.XZCE',
 'CJ9999.XZCE',
 'CS9999.XDCE',
 'CU9999.XSGE',
 'CY9999.XZCE',
 'EB9999.XDCE',
 'EG9999.XDCE',
 'ER9999.XZCE',
 'FB9999.XDCE',
 'FG9999.XZCE',
 'FU9999.XSGE',
 'GN9999.XZCE',
 'HC9999.XSGE',
 'I9999.XDCE',
 'IC9999.CCFX',
 'IF9999.CCFX',
 'IH9999.CCFX',
 'J9999.XDCE',
 'JD9999.XDCE',
 'JM9999.XDCE',
 'JR9999.XZCE',
 'L9999.XDCE',
 'LR9999.XZCE',
 'M9999.XDCE',
 'MA9999.XZCE',
 'ME9999.XZCE',
 'NI9999.XSGE',
 'NR9999.XINE',
 'OI9999.XZCE',
 'P9999.XDCE',
 'PB9999.XSGE',
 'PM9999.XZCE',
 'PP9999.XDCE',
 'RB9999.XSGE',
 'RI9999.XZCE',
 'RM9999.XZCE',
 'RO9999.XZCE',
 'RR9999.XDCE',
 'RS9999.XZCE',
 'RU9999.XSGE',
 'SC9999.XINE',
 'SF9999.XZCE',
 'SM9999.XZCE',
 'SN9999.XSGE',
 'SP9999.XSGE',
 'SR9999.XZCE',
 'SS9999.XSGE',
 'T9999.CCFX',
 'TA9999.XZCE',
 'TC9999.XZCE',
 'TF9999.CCFX',
 'TS9999.CCFX',
 'UR9999.XZCE',
 'V9999.XDCE',
 'WH9999.XZCE',
 'WR9999.XSGE',
 'WS9999.XZCE',
 'WT9999.XZCE',
 'Y9999.XDCE',
 'ZC9999.XZCE',
 'ZN9999.XSGE']

In [86]:
# J9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/J9999.csv")

In [87]:
# JD9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/JD9999.csv")

In [88]:
# JM9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/JM9999.csv")

In [62]:
# IF9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/IF9999.csv")

In [27]:
# A9999
# AG9999
# AL9999
# AP9999
# AU9999
# B9999
# BB9999 
# BU9999
# C9999
# CF9999
# CJ9999
# CS9999
# CU9999
# CY9999
# EB9999
# EG9999
# ER9999
# FB9999
# FG9999
# FU9999
# GN9999 
# HC9999 
# I9999 
# IC9999 
# IF9999 
# IH9999 
# J9999 
# JD9999 
# JM9999

# list2 = [
# JR9999,L9999, 
# SN9999, SP9999, SR9999, T9999, TA9999, TC9999,
# TF9999,TS9999,UR9999, V9999,WH9999,WR9999,WS9999,WT9999,Y9999,ZC9999,ZN9999]
# list3 = [
# 'JR9999','L9999', 
# 'SN9999', 'SP9999', 'SR9999', 'T9999', 'TA9999', 'TC9999',
# 'TF9999','TS9999','UR9999', 'V9999','WH9999','WR9999','WS9999','WT9999','Y9999','ZC9999','ZN9999']




# LR9999,M9999  ,MA9999 ,ME9999 ,NI9999 ,NR9999 ,OI9999 ,P9999, PB9999,
## PM9999 PP9999 ,RB9999 ,RI9999 ,RM9999 ,RO9999 ,RR9999 ,RS9999,RU9999,SC9999,
# , SS9999
#      SF9999,SM9999,
SF9999

,date,open,close,high,low,volume,money,open_interest
0,2014-08-11 09:01:00,5768.0,5790.0,5796.0,5768.0,1260.0,36362080.0,31214
1,2014-08-11 09:02:00,5792.0,5808.0,5808.0,5792.0,918.0,26552260.0,31636
2,2014-08-11 09:03:00,5808.0,5802.0,5810.0,5800.0,1126.0,32615180.0,31798
3,2014-08-11 09:04:00,5802.0,5798.0,5802.0,5796.0,352.0,10200960.0,31702
4,2014-08-11 09:05:00,5796.0,5782.0,5798.0,5780.0,612.0,17735040.0,31672
5,2014-08-11 09:06:00,5784.0,5780.0,5786.0,5778.0,742.0,21495280.0,31906
6,2014-08-11 09:07:00,5780.0,5792.0,5792.0,5776.0,830.0,24036800.0,31880
7,2014-08-11 09:08:00,5794.0,5784.0,5798.0,5782.0,270.0,7819200.0,31952
8,2014-08-11 09:09:00,5782.0,5794.0,5794.0,5782.0,342.0,9904320.0,31972
9,2014-08-11 09:10:00,5796.0,5792.0,5800.0,5792.0,758.0,21951680.0,32038
10,2014-08-11 09:11:00,5792.0,5792.0,5796.0,5792.0,168.0,4865280.0,31994
11,2014-08-11 09:12:00,5792.0,5792.0,5794.0,5790.0,250.0,7240000.0,32010
12,2014-08-11 09:13:00,5792.0,5794.0,5794.0,5792.0,106.0,3069760.0,32054
13,2014-08-11 09:14:00,5794.0,5802.0,5802.0,5794.0,372.0,10773120.0,32292
14,2014-08-11 09:15:00,5802.0,5794.0,5802.0,5794.0,296.0,8572160.0,32314
15,2014-08-11 09:16:00,5794.0,5798.0,5798.0,5794.0,162.0,4691520.0,32356
16,2014-08-11 09:17:00,5798.0,5796.0,5800.0,5794.0,122.0,3533120.0,32400
17,2014-08-11 09:18:00,5794.0,5802.0,5806.0,5794.0,860.0,24909700.0,32582
18,2014-08-11 09:19:00,5802.0,5802.0,5806.0,5800.0,386.0,11182420.0,32694
19,2014-08-11 09:20:00,5802.0,5802.0,5804.0,5800.0,154.0,4461380.0,32748
20,2014-08-11 09:21:00,5802.0,5800.0,5802.0,5800.0,344.0,9965680.0,32874
21,2014-08-11 09:22:00,5800.0,5802.0,5802.0,5800.0,120.0,3476400.0,32888
22,2014-08-11 09:23:00,5802.0,5804.0,5804.0,5800.0,128.0,3708160.0,32962
23,2014-08-11 09:24:00,5802.0,5802.0,5804.0,5802.0,84.0,2433480.0,33032
24,2014-08-11 09:25:00,5804.0,5806.0,5806.0,5802.0,96.0,2781120.0,33094
25,2014-08-11 09:26:00,5806.0,5812.0,5816.0,5806.0,1254.0,36339360.0,33120
26,2014-08-11 09:27:00,5812.0,5810.0,5814.0,5806.0,458.0,13272840.0,33132
27,2014-08-11 09:28:00,5810.0,5808.0,5812.0,5806.0,248.0,7187040.0,33132
28,2014-08-11 09:29:00,5806.0,5802.0,5806.0,5802.0,362.0,10494380.0,33062
29,2014-08-11 09:30:00,5802.0,5802.0,5806.0,5800.0,276.0,8001240.0,33010
...,...,...,...,...,...,...,...,...
267720,2019-06-28 14:31:00,6188.0,6186.0,6190.0,6184.0,334.0,10337300.0,187960
267721,2019-06-28 14:32:00,6186.0,6186.0,6188.0,6184.0,68.0,2104600.0,187958
267722,2019-06-28 14:33:00,6186.0,6188.0,6188.0,6186.0,72.0,2228400.0,187980
267723,2019-06-28 14:34:00,6186.0,6186.0,6188.0,6186.0,34.0,1052300.0,187976
267724,2019-06-28 14:35:00,6186.0,6186.0,6188.0,6186.0,82.0,2537900.0,187966
267725,2019-06-28 14:36:00,6186.0,6188.0,6190.0,6186.0,120.0,3714000.0,187950
267726,2019-06-28 14:37:00,6188.0,6188.0,6190.0,6186.0,64.0,1980800.0,187958
267727,2019-06-28 14:38:00,6188.0,6188.0,6188.0,6186.0,70.0,2166500.0,187952
267728,2019-06-28 14:39:00,6188.0,6192.0,6192.0,6188.0,116.0,3590200.0,187972
267729,2019-06-28 14:40:00,6192.0,6192.0,6194.0,6188.0,158.0,4890100.0,187956
267730,2019-06-28 14:41:00,6196.0,6200.0,6200.0,6194.0,380.0,11761000.0,187844
267731,2019-06-28 14:42:00,6198.0,6198.0,6200.0,6196.0,172.0,5323400.0,187878
267732,2019-06-28 14:43:00,6198.0,6200.0,6200.0,6196.0,134.0,4147300.0,187864
267733,2019-06-28 14:44:00,6200.0,6200.0,6200.0,6196.0,128.0,3961600.0,187886
267734,2019-06-28 14:45:00,6200.0,6202.0,6202.0,6198.0,168.0,5199600.0,187862
267735,2019-06-28 14:46:00,6202.0,6200.0,6204.0,6198.0,386.0,11946700.0,188030
267736,2019-06-28 14:47:00,6200.0,6206.0,6206.0,6198.0,242.0,7489900.0,187988
267737,2019-06-28 14:48:00,6206.0,6206.0,6208.0,6204.0,214.0,6623300.0,188026
267738,2019-06-28 14:49:00,6206.0,6208.0,6210.0,6206.0,332.0,10275400.0,188140
267739,2019-06-28 14:50:00,6208.0,6216.0,6216.0,6208.0,540.0,16713000.0,188278
267740,2019-06-28 14:51:00,6216.0,6218.0,6218.0,6212.0,198.0,6128100.0,188326
267741,2019-06-28 14:52:00,6218.0,6214.0,6218.0,6214.0,174.0,5385300.0,188292
267742,2019-06-28 14:53:00,6216.0,6214.0,6220.0,6214.0,408.0,12627600.0,188260
267743,2019-06-28 14:54:00,6216.0,6222.0,6222.0,6214.0,984.0,30454800.0,188120
267744,2019-06-28 14:55:00,6222.0,6222.0,6222.0,6218.0,402.0,12441900.0,187886
267745,2019-06-28 14:56:00,6218.0,6218.0,6222.0,6216.0,236.0,7304200.0,187808
267746,2019-06-28 14:57:00,6218.0,6222.0,6222.0,6216.0,254.0,7861300.0,187832
267747,2019-06-28 14:58:00,6222.0,6220.0,6224.0,6220.0,334.0,10337300.0,187776
267748,2019-06-28 14:59:00,6220.0,6224.0,6228.0,6220.0,554.0,18145920.0,187722
267749,2019-06-28 15:00:00,6222.0,6218.0,6230.0,6218.0,1204.0,37275840.0,187756

In [28]:
# JR9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/JR9999.csv")
SM9999

,date,open,close,high,low,volume,money,open_interest
0,2014-08-11 09:01:00,6444.0,6466.0,6486.0,6444.0,1398.0,45120020.0,25108
1,2014-08-11 09:02:00,6468.0,6456.0,6472.0,6456.0,638.0,20624240.0,25456
2,2014-08-11 09:03:00,6458.0,6478.0,6484.0,6458.0,1012.0,32714720.0,25526
3,2014-08-11 09:04:00,6478.0,6468.0,6480.0,6466.0,172.0,5562480.0,25602
4,2014-08-11 09:05:00,6466.0,6430.0,6468.0,6426.0,1674.0,54104640.0,26220
5,2014-08-11 09:06:00,6430.0,6420.0,6436.0,6414.0,2874.0,92740060.0,26114
6,2014-08-11 09:07:00,6420.0,6426.0,6430.0,6416.0,1360.0,43833540.0,26276
7,2014-08-11 09:08:00,6428.0,6426.0,6432.0,6426.0,620.0,19976400.0,26664
8,2014-08-11 09:09:00,6426.0,6444.0,6444.0,6426.0,486.0,15658920.0,26658
9,2014-08-11 09:10:00,6444.0,6426.0,6444.0,6424.0,532.0,17136580.0,26736
10,2014-08-11 09:11:00,6428.0,6432.0,6436.0,6426.0,574.0,18488540.0,26728
11,2014-08-11 09:12:00,6434.0,6438.0,6440.0,6432.0,558.0,17973180.0,26790
12,2014-08-11 09:13:00,6438.0,6430.0,6440.0,6430.0,388.0,12497480.0,27004
13,2014-08-11 09:14:00,6432.0,6452.0,6452.0,6430.0,754.0,24286340.0,26682
14,2014-08-11 09:15:00,6452.0,6448.0,6454.0,6446.0,650.0,20936500.0,26776
15,2014-08-11 09:16:00,6448.0,6458.0,6458.0,6444.0,862.0,27765020.0,26922
16,2014-08-11 09:17:00,6458.0,6456.0,6464.0,6456.0,822.0,26480420.0,26966
17,2014-08-11 09:18:00,6456.0,6454.0,6460.0,6452.0,670.0,21587400.0,27366
18,2014-08-11 09:19:00,6456.0,6460.0,6466.0,6456.0,632.0,20363040.0,27166
19,2014-08-11 09:20:00,6460.0,6462.0,6462.0,6458.0,240.0,7732800.0,27250
20,2014-08-11 09:21:00,6462.0,6458.0,6464.0,6458.0,370.0,11924680.0,27246
21,2014-08-11 09:22:00,6458.0,6452.0,6462.0,6452.0,318.0,10249140.0,27258
22,2014-08-11 09:23:00,6452.0,6452.0,6454.0,6446.0,516.0,16630680.0,27420
23,2014-08-11 09:24:00,6452.0,6454.0,6456.0,6450.0,182.0,5865860.0,27420
24,2014-08-11 09:25:00,6454.0,6460.0,6462.0,6454.0,122.0,3932060.0,27418
25,2014-08-11 09:26:00,6458.0,6464.0,6464.0,6456.0,546.0,17597580.0,27492
26,2014-08-11 09:27:00,6464.0,6460.0,6464.0,6458.0,380.0,12247400.0,27660
27,2014-08-11 09:28:00,6460.0,6462.0,6464.0,6460.0,116.0,3738680.0,27658
28,2014-08-11 09:29:00,6462.0,6460.0,6464.0,6460.0,142.0,4576660.0,27688
29,2014-08-11 09:30:00,6458.0,6454.0,6458.0,6452.0,252.0,8121960.0,27644
...,...,...,...,...,...,...,...,...
267720,2019-06-28 14:31:00,7786.0,7776.0,7786.0,7774.0,358.0,13897560.0,155040
267721,2019-06-28 14:32:00,7774.0,7778.0,7778.0,7774.0,184.0,7142880.0,154930
267722,2019-06-28 14:33:00,7776.0,7780.0,7782.0,7776.0,290.0,11257800.0,154902
267723,2019-06-28 14:34:00,7778.0,7780.0,7780.0,7776.0,118.0,4580760.0,154852
267724,2019-06-28 14:35:00,7780.0,7780.0,7780.0,7778.0,150.0,5823000.0,154864
267725,2019-06-28 14:36:00,7780.0,7782.0,7784.0,7780.0,188.0,7298160.0,154938
267726,2019-06-28 14:37:00,7784.0,7780.0,7784.0,7780.0,106.0,4114920.0,154876
267727,2019-06-28 14:38:00,7780.0,7780.0,7782.0,7780.0,100.0,3882000.0,154848
267728,2019-06-28 14:39:00,7782.0,7780.0,7782.0,7778.0,148.0,5745360.0,154796
267729,2019-06-28 14:40:00,7780.0,7784.0,7784.0,7780.0,98.0,3804360.0,154738
267730,2019-06-28 14:41:00,7782.0,7780.0,7784.0,7778.0,92.0,3571440.0,154712
267731,2019-06-28 14:42:00,7782.0,7778.0,7782.0,7776.0,408.0,15838560.0,154704
267732,2019-06-28 14:43:00,7778.0,7774.0,7778.0,7770.0,238.0,9239160.0,154682
267733,2019-06-28 14:44:00,7774.0,7774.0,7774.0,7770.0,32.0,1242240.0,154688
267734,2019-06-28 14:45:00,7772.0,7780.0,7780.0,7770.0,100.0,3882000.0,154632
267735,2019-06-28 14:46:00,7780.0,7776.0,7780.0,7774.0,166.0,6444120.0,154556
267736,2019-06-28 14:47:00,7776.0,7776.0,7776.0,7774.0,138.0,5357160.0,154462
267737,2019-06-28 14:48:00,7776.0,7772.0,7776.0,7772.0,154.0,5978280.0,154332
267738,2019-06-28 14:49:00,7772.0,7768.0,7772.0,7766.0,300.0,11646000.0,154120
267739,2019-06-28 14:50:00,7770.0,7770.0,7776.0,7768.0,146.0,5667720.0,154138
267740,2019-06-28 14:51:00,7772.0,7770.0,7772.0,7766.0,104.0,4037280.0,154090
267741,2019-06-28 14:52:00,7770.0,7764.0,7770.0,7764.0,94.0,3649080.0,154048
267742,2019-06-28 14:53:00,7764.0,7766.0,7768.0,7764.0,94.0,3649080.0,154028
267743,2019-06-28 14:54:00,7766.0,7770.0,7770.0,7766.0,112.0,4347840.0,153944
267744,2019-06-28 14:55:00,7770.0,7774.0,7778.0,7770.0,272.0,10559040.0,153782
267745,2019-06-28 14:56:00,7776.0,7776.0,7780.0,7772.0,240.0,9316800.0,153720
267746,2019-06-28 14:57:00,7778.0,7776.0,7778.0,7774.0,226.0,8773320.0,153712
267747,2019-06-28 14:58:00,7776.0,7770.0,7776.0,7770.0,202.0,7841640.0,153586
267748,2019-06-28 14:59:00,7770.0,7776.0,7778.0,7770.0,282.0,10947240.0,153396
267749,2019-06-28 15:00:00,7774.0,7774.0,7778.0,7770.0,416.0,16149120.0,153118

In [56]:
# L9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/L9999.csv")
# SN9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/SN9999.csv")
# SP9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/SP9999csv")
# SR9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/SR9999.csv")
# T9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/T9999.csv")

In [57]:
# TA9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/TA9999.csv")
# TC9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/TC9999.csv")
# TF9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/TF9999.csv")
# TS9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/TS9999.csv")
# UR9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/UR9999.csv")
# V9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/V9999.csv")
# WH9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/WH9999.csv")
# WR9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/WR9999.csv")

In [58]:
# WS9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/WS9999.csv")
# WT9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/WT9999.csv")
# Y9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/Y9999.csv")
# ZC9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/ZC9999.csv")
# ZN9999.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/ZN9999.csv")

In [52]:
list3

['JR9999',
 'L9999',
 'SN9999',
 'SP9999',
 'SR9999',
 'T9999',
 'TA9999',
 'TC9999',
 'TF9999',
 'TF9999',
 'TS9999',
 'UR9999',
 'V9999',
 'WH9999',
 'WR9999',
 'WS9999',
 'WT9999',
 'Y9999',
 'ZC9999',
 'ZN9999']

In [55]:
for i in list2:
    print(np.where(i))

(array([     0,      0,      0, ..., 308024, 308024, 308024]), array([0, 1, 2, ..., 2, 3, 4]))
(array([     0,      0,      0, ..., 659009, 659009, 659009]), array([0, 1, 2, ..., 5, 6, 7]))
(array([     0,      0,      0, ..., 475469, 475469, 475469]), array([0, 1, 2, ..., 5, 6, 7]))
(array([    0,     0,     0, ..., 48164, 48164, 48164]), array([0, 1, 2, ..., 5, 6, 7]))
(array([     0,      0,      0, ..., 916574, 916574, 916574]), array([0, 1, 2, ..., 5, 6, 7]))
(array([     0,      0,      0, ..., 281609, 281609, 281609]), array([0, 1, 2, ..., 5, 6, 7]))

KeyboardInterrupt:

In [47]:
for i in list2:
        i.to_csv("/Users/tjmask/Desktop/quantitative strategy/data/%d.csv",)

TypeError: "delimiter" must be string, not DataFrame

In [78]:
price_df2.index

MultiIndex(levels=[['A9999.XDCE', 'AG9999.XSGE', 'AL9999.XSGE'], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],
           codes=[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [80]:
all_info.head()

NameError: name 'all_info' is not defined

In [ ]:
# stocks = list(get_all_securities(['stock']).index)
# security_list = stocks[:100]
# start_date = '2010-01-01'
# end_date = '2019-011-20'
# price_df = get_price(security_list[:50], start_date=start_date, end_date=end_date, 
#                      frequency='minute', fields=['close', 'money'], skip_paused=False, fq='pre', count=None)